class configs:
    TIME_SPENT = 'TimeSpent'
    AGE = 'Age'
    AREA_INCOME = 'AreaIncome'
    DAILY_INTERNET_USAGE = 'DailyInternetUsage'
    ADHEADLINE = 'AdHeadline'
    CITY ='City'
    MALE ='Male'
    COUNTRY ='Country'
    CLICKED = 'Clicked'
    TIMESTAMP = 'Timestamp'
    FILEPATH_ADVERTISING_CLEANED = '../C_Data/advertising_cleaned.csv'
    ADJ_CLOSE = 'Adj Close'
    THETAS = 'thetas'
    RS = 'rs'
    RECOVERY = 'recovery'
    DEATH = 'death'
